### ISSUE TITLE
Parameter set are not used for encoding, no error message

### ISSUE THREAD

**Issue by quamt** [rigaya/NVEnc#535] opened 2023-11-11 08:06 UTC
I try to encode video with the following parameter:

```
--avhw
--codec hevc 
--preset quality
--profile main10
--qp-init 20:23:25
--qp-min 20:23:25
--qp-max 22:25:27
--preset P7 
--output-depth 10 
--lookahead 32 
--bframes 5 
--ref 8
--multiref-l0 3 
--multiref-l1 3 
--bref-mode each
--mv-precision Q-pel
--pic-struct
--split-enc auto
--vpp-convolution3d matrix=simple 
--vpp-knn radius=3,strength=0.10,lerp=0.1 
--vpp-unsharp weight=1.0 
--vpp-edgelevel strength=10.0,threshold=16.0
--vpp-deband range=15,sample=1,thre_y=15,thre_cb=15,thre_cr=15,dither_y=12,dither_c=12,rand_each_frame
--audio-copy
--chapter-copy
```

Some parameter are not used and I am confused as why it is not the case.

Here what I see in the CMD

```
NVEncC (x64) 7.35 (r2612) by rigaya, Oct 28 2023 09:22:54 (VC 1929/Win)
OS Version     Windows 11 x64 (22621) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [5.02GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 3080 (8704 cores, 1725 MHz)[PCIe4x16][546.01]
NVENC / CUDA   NVENC API 12.1, CUDA 12.3, schedule mode: auto
Input Buffers  CUDA, 46 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24/1 fps
AVSync         vfr
Vpp Filters    cspconv(nv12 -> yv12(16bit))
               convolution3d: matrix simple, mode normal
                       threshold spatial luma 5, chroma 6, temporal luma 4, chroma 5
               deband: mode 1, range 15, threY 15, threCb 15, threCr 15
                       ditherY 15, ditherC 15, blurFirst no, randEachFrame no
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               1920x1080p 1:1 24.000fps (24/1fps)
               avwriter: hevc, eac3 => matroska
Encoder Preset quality
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 24000 kbps)
Target Quality 25.00
Initial QP     I:20  P:23  B:25
QP range       I:18-22  P:21-25  B:23-27
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       5 frames [ref mode: each]
Ref frames     8 frames, MultiRef L0:3 L1:3
AQ             off
CU max / min   auto / auto
Others         mv:Q-pel pic-struct buf-period
```

**Comment by quamt** [comment] 2023-11-11 08:17
I tested with other settings

```
--avhw
--codec hevc 
--preset quality
--profile main10
--vbr-quality 30
--max-bitrate 5000
--vbv-bufsize 6000
--multipass 2pass-full
--weightp
--aq
--aq-temporal
--hierarchial-p
--hierarchial-b
--mv-precision Q-pel
--preset P7 
--output-depth 10 
--lookahead 32 
--bframes 5 
--ref 8
--multiref-l0 3 
--multiref-l1 3 
--bref-mode each
--mv-precision Q-pel
--pic-struct
--split-enc auto
--vpp-convolution3d matrix=simple 
--vpp-knn radius=3,strength=0.10,lerp=0.1 
--vpp-unsharp weight=1.0 
--vpp-edgelevel strength=10.0,threshold=16.0
--vpp-deband range=15,sample=1,thre_y=15,thre_cb=15,thre_cr=15,dither_y=12,dither_c=12,rand_each_frame
--audio-copy
--chapter-copy

```

CMD shows this:

```
NVEncC (x64) 7.35 (r2612) by rigaya, Oct 28 2023 09:22:54 (VC 1929/Win)
OS Version     Windows 11 x64 (22621) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [4.92GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 3080 (8704 cores, 1725 MHz)[PCIe4x16][546.01]
NVENC / CUDA   NVENC API 12.1, CUDA 12.3, schedule mode: auto
Input Buffers  CUDA, 20 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24/1 fps
AVSync         vfr
Vpp Filters    copyDtoD
Output Info    H.264/AVC high @ Level auto
               1920x1080p 1:1 24.000fps (24/1fps)
               avwriter: h264 => matroska
Encoder Preset default
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 24000 kbps)
Target Quality 25.00
Initial QP     I:20  P:23  B:25
QP range       I:0-51  P:0-51  B:0-51
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      off
GOP length     240 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             off
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto
```

**Comment by rigaya** [comment] 2023-11-11 12:37
The first one, I was not able to reproduce your issue (vpp-knn,unsharp,edgelevel ignored?).

Parsing seems fine for me like below, can be checked by ```--debug-cmd-parser```.

```
Y:\Encoders>x64\NVEncC64.exe -i sakura_op.mpg -o F:\temp\test.mp4 --debug-cmd-parser --option-file F:\temp\nvenc_prm.txt
arg[  1]: -i
arg[  2]: sakura_op.mpg
arg[  3]: -o
arg[  4]: F:\temp\test.mp4
arg[  5]: --debug-cmd-parser
arg[  6]: --option-file
arg[  7]: F:\temp\nvenc_prm.txt
arg[  8]: --avhw
arg[  9]: --codec
arg[ 10]: hevc
arg[ 11]: --preset
arg[ 12]: quality
arg[ 13]: --profile
arg[ 14]: main10
arg[ 15]: --qp-init
arg[ 16]: 20:23:25
arg[ 17]: --qp-min
arg[ 18]: 20:23:25
arg[ 19]: --qp-max
arg[ 20]: 22:25:27
arg[ 21]: --preset
arg[ 22]: P7
arg[ 23]: --output-depth
arg[ 24]: 10
arg[ 25]: --lookahead
arg[ 26]: 32
arg[ 27]: --bframes
arg[ 28]: 5
arg[ 29]: --ref
arg[ 30]: 8
arg[ 31]: --multiref-l0
arg[ 32]: 3
arg[ 33]: --multiref-l1
arg[ 34]: 3
arg[ 35]: --bref-mode
arg[ 36]: each
arg[ 37]: --mv-precision
arg[ 38]: Q-pel
arg[ 39]: --pic-struct
arg[ 40]: --split-enc
arg[ 41]: auto
arg[ 42]: --vpp-convolution3d
arg[ 43]: matrix=simple
arg[ 44]: --vpp-knn
arg[ 45]: radius=3,strength=0.10,lerp=0.1
arg[ 46]: --vpp-unsharp
arg[ 47]: weight=1.0
arg[ 48]: --vpp-edgelevel
arg[ 49]: strength=10.0,threshold=16.0
arg[ 50]: --vpp-deband
arg[ 51]: range=15,sample=1,thre_y=15,thre_cb=15,thre_cr=15,dither_y=12,dither_c=12,rand_each_frame
arg[ 52]: --audio-copy
arg[ 53]: --chapter-copy
parsing   1: -i
parsing   3: -o
parsing   5: --debug-cmd-parser
parsing   6: --option-file
parsing   8: --avhw
parsing   9: --codec
parsing  11: --preset
parsing  13: --profile
parsing  15: --qp-init
parsing  17: --qp-min
parsing  19: --qp-max
parsing  21: --preset
parsing  23: --output-depth
parsing  25: --lookahead
parsing  27: --bframes
parsing  29: --ref
parsing  31: --multiref-l0
parsing  33: --multiref-l1
parsing  35: --bref-mode
parsing  37: --mv-precision
parsing  39: --pic-struct
parsing  40: --split-enc
parsing  42: --vpp-convolution3d
parsing  44: --vpp-knn
parsing  46: --vpp-unsharp
parsing  48: --vpp-edgelevel
parsing  50: --vpp-deband
parsing  52: --audio-copy
parsing  53: --chapter-copy
--------------------------------------------------------------------------------
F:\temp\test.mp4
--------------------------------------------------------------------------------
NVEncC (x64) 7.36 (r2615) by rigaya, Nov  4 2023 18:32:38 (VC 1929/Win)
OS Version     Windows 11 x64 (22631) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [4.90GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4080 (9728 cores, 2505 MHz)[PCIe4x16][545.92]
NVENC / CUDA   NVENC API 12.1, CUDA 12.3, schedule mode: auto
Input Buffers  CUDA, 46 frames
Input Info     avcuvid: MPEG1, 1280x720, 30/1 fps
Vpp Filters    cspconv(nv12 -> yv12(16bit))
               convolution3d: matrix simple, mode normal
                       threshold spatial luma 3, chroma 4, temporal luma 3, chroma 4
               denoise(knn): radius 3, strength 0.10, lerp 0.10
                              th_weight 0.01, th_lerp 0.80
               unsharp: radius 3, weight 1.0, threshold 10.0
               edgelevel: strength 10.0, threshold 16.0, black 0.0, white 0.0
               deband: mode 1, range 15, threY 15, threCb 15, threCr 15
                       ditherY 12, ditherC 12, blurFirst no, randEachFrame yes
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               1280x720p 1:1 30.000fps (30/1fps)
               avwriter: hevc, mp2 => mp4
Encoder Preset quality
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 11520 kbps)
Target Quality 25.00
Initial QP     I:20  P:23  B:25
QP range       I:20-22  P:23-25  B:25-27
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     300 frames
B frames       5 frames [ref mode: each]
Ref frames     8 frames, MultiRef L0:3 L1:3
AQ             off
CU max / min   auto / auto
Others         mv:Q-pel pic-struct buf-period
```

The second one, there is a problem ```--max-bitrate``` ignored, seems to be bug from NVEnc 7.35, I'll fix it in the future version.

**Comment by quamt** [comment] 2023-11-12 03:13
I tested 7.36 and had the same problems.

I went back to 7.33 and testing it now.

**Comment by rigaya** [comment] 2023-11-19 12:34
--max-bitrate not working with --qvbr should have been fixed with [NVEnc 7.37](https://github.com/rigaya/NVEnc/releases/tag/7.37).

It also improves ```--debug-cmd-parser```, now will show if the options were parsed properly. Please try with ```--debug-cmd-parser``` to check if the options were parsed properly.

**Comment by quamt** [comment] 2023-11-20 01:11
ok will test it and report back

**Comment by quamt** [comment] 2023-11-20 03:28
confirmed max bitrate works now 

```
parsing   1: -i: OK
parsing   3: --codec: OK
parsing   5: --preset: OK
parsing   7: --output-depth: OK
parsing   9: --vbr: OK
parsing  11: --max-bitrate: OK
parsing  13: --colormatrix: OK
parsing  15: --colorprim: OK
parsing  17: --transfer: OK
parsing  19: --chromaloc: OK
parsing  21: --max-cll: OK
parsing  23: --master-display: OK
parsing  25: --audio-codec: OK
parsing  27: --audio-bitrate: OK
parsing  29: --debug-cmd-parser: OK
parsing  30: --output: OK
```

**Closed** 2023-11-20 03:46 UTC
