### ISSUE TITLE
Error 15

### ISSUE THREAD

**Issue by kramadana2** [rigaya/NVEnc#74] opened 2018-09-25 11:51 UTC
I get the following error when trying the command NVEncC.exe --check-features

Error on nvEncGetEncodePresetConfig: 15 (NVENC indicates that an invalid struct version was used by the client)
Error on nvEncGetEncodePresetConfig: 15 (NVENC indicates that an invalid struct version was used by the client)

Environment Info
OS : Windows 10 x64 (17134)
CPU: AMD A10 PRO-7850B R7, 12 Compute Cores 4C+8G @ 3.69GHz (2C/4T)
RAM: Used 3834 MB, Total 16304 MB
GPU: 388.13 (6 EU) @ 1392 MHz (388.13)

List of available features.
Codec: H.264/AVC
Max Bframes               4
B Ref Mode                yes
RC Modes                  63
Field Encoding            yes
MonoChrome                no
FMO                       no
Quater-Pel MV             yes
B Direct Mode             yes
CABAC                     yes
Adaptive Transform        yes
Max Temporal Layers       0
Hierarchial P Frames      no
Hierarchial B Frames      no
Max Level                 51
Min Level                 1
4:4:4                     yes
Max Width                 4096
Max Height                4096
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      yes
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   65536
Lossless                  yes
SAO                       no
Me Only Mode              yes
Lookahead                 yes
AQ (temporal)             yes
Weighted Prediction       yes
Max LTR Frames            8
10bit depth               no

Codec: H.265/HEVC
Max Bframes               0
RC Modes                  63
Field Encoding            no
MonoChrome                no
Quater-Pel MV             yes
B Direct Mode             no
Max Temporal Layers       0
Hierarchial P Frames      no
Hierarchial B Frames      no
Max Level                 62
Min Level                 1
4:4:4                     yes
Max Width                 8192
Max Height                8192
Dynamic Resolution Change yes
Dynamic Bitrate Change    yes
Forced constant QP        yes
Dynamic RC Mode Change    no
Subframe Readback         yes
Constrained Encoding      no
Intra Refresh             yes
Custom VBV Bufsize        yes
Dynamic Slice Mode        yes
Ref Pic Invalidiation     yes
PreProcess                no
Async Encoding            yes
Max MBs                   262144
Lossless                  yes
SAO                       yes
Me Only Mode              yes
Lookahead                 yes
AQ (temporal)             no
Weighted Prediction       yes
Max LTR Frames            7
10bit depth               yes

**Comment by rigaya** [comment] 2018-09-26 12:58
NVEnc 4.00 or later  requires NVIDIA graphics driver 390.77 or later. (You seem to have 388.13).
Please update your driver and try again.

**Comment by rigaya** [comment] 2018-10-08 12:27
I will close this issue, please re-open if you have any more related problems.

**Closed by rigaya** 2018-10-08 12:27 UTC

**Comment by drSHLEFF** [comment] 2020-03-25 06:25
nvenc : Error on nvEncGetEncodePresetConfig: 4 (NVENC this indicates that device passed to the API call is invalid)

Driver 445.75

**Comment by rigaya** [comment] 2020-03-25 13:55
I've updated to [NVEnc 4.69](https://github.com/rigaya/NVEnc/releases/tag/4.69), avoiding this error message caused by driver 445.75.

**Comment by drSHLEFF** [comment] 2020-03-25 14:06
I confirm, the error is resolved 👍
