### ISSUE TITLE
Audio filtergraph error

### ISSUE THREAD

**Issue by sweetngx** [rigaya/NVEnc#390] opened 2022-04-24 14:11 UTC
When I try to encode the video in the source below with ac3, I get the error (`avout: failed to feed the audio filtergraph`)  --audio-ignore-decode-error 10, but it didn't solve my problem. How can I bypass errors like this completely?

When I use audio-ignore-decode-error and check the file with mediainfo, it says "`IsTruncated`". So it thinks that the file is not closed correctly.

```
"@type": "Audio",
"StreamOrder": "1",
"ID": "2",
"UniqueID": "16085062927675739563",
"Format": "DTS",
"Format_Settings_Mode": "16",
"Format_Settings_Endianness": "Big",
"CodecID": "A_DTS",
"Duration": "5628.224000000",
"BitRate_Mode": "CBR",
"BitRate": "1509000",
"Channels": "2",
"ChannelPositions": "Front: L R",
"ChannelLayout": "L R",
"SamplesPerFrame": "512",
"SamplingRate": "48000",
"SamplingCount": "270154752",
"FrameRate": "93.750",
"FrameCount": "527646",
"BitDepth": "16",
"Compression_Mode": "Lossy",
"Delay": "0.000",
"Delay_Source": "Container",
"StreamSize": "1061623816",
"StreamSize_Proportion": "0.15082",
"Title": "phll & aktrk",
"Language": "en",
"Default": "Yes",
"Forced": "No"
},
```

**Comment by sweetngx** [comment] 2022-04-24 15:25
When I use audio-ignore-decode-error and check the file with mediainfo, it says "IsTruncated". So it thinks that the file is not closed correctly.

**Comment by rigaya** [comment] 2022-04-25 13:06
--audio-ignore-decode-error is an option to simply ignore decode error for partially corrupted input files, which not might be the case for this time.

I'm not sure of the cause of ```failed to feed the audio filtergraph```, it might be related with the input file or the command line options. Would you please share the full command line used in this case?

**Comment by rigaya** [comment] 2024-08-04 04:48
I'm sorry but I'll close this issue, as I were not able to find out the cause and reproduce the issue.

**Closed by rigaya** 2024-08-04 04:48 UTC
