### ISSUE TITLE
Profile Main10 doesn't work right after driver 555.85

### ISSUE THREAD

**Issue by intellq** [rigaya/NVEnc#590] opened 2024-05-27 02:52 UTC
With driver 555.85, the following command line:

**nvencc64 -i movie.mkv -c hevc --profile main10 --vbr 20000 -o video.hevc**

Creates a file with wrong bitrate (and size). The resulting file would be with ~5000 kbps, instead of 20000.

Reverting back to 554.42 (or any older driver) results in a file being created with the right size/bitrate.

Tested nvencc 7.53 and 7.51, same behavior.

**Comment by rigaya** [comment] 2024-05-27 10:04
I suppose something weird going on with the new driver, as I also can reproduce the issue by just updating the driver.

At this time. I can only suggest a workaround, please have a try adding ```--qp-min 1```.

**Comment by intellq** [comment] 2024-05-27 12:50
Thanks for the quick reply.

"qp-min=1" seems to fix the issue.

Can you explain what it does, instead of the "unset" default?

**Comment by rigaya** [comment] 2024-05-27 13:59
Nice to hear the workaround works. I’ll make that default in the next release.

qs-min simply sets minimum value of the qp. qp-min 1 should be same as unset (no limit), but somehow it seems like that the new driver is doing something weird when unset.

**Comment by rigaya** [comment] 2024-05-28 12:58
[NVEnc](https://github.com/rigaya/NVEnc/releases/tag/7.54) will apply "--qp-min 0" by default, so will have no problem with 555.85 driver.

(Previously I suggested to apply ```--qp-min 1```, but after further testing ```--qp-min 0``` also seems ok, so I've made ```--qp-min 0``` default)

Thank you for your report, I'll close this issue as the problem was solved.

**Closed by rigaya** 2024-05-28 12:58 UTC

**Comment by k4oma** [comment] 2024-06-03 15:55
--qp-min 1 or --qp-min 0 do not work with [ Forced 3-split frame enconding (if NVENC > 2, NVENC no of strings otherwise) Encoding bitrate much greater than CBR set at 3500kbps. ~1800kbps Min. during encoding.

**Comment by k4oma** [comment] 2024-06-03 16:01
--qp-min 0 and qp-min 1 do not work with [Forced 3 strip split frame encoding set.] CBR bitrate of 3500kbps becomes excessive during hardware encoding. < 18000kbps.
