### ISSUE TITLE
Audio problems with MKV and TrueHD/AC3

### ISSUE THREAD

**Issue by agressiv** [rigaya/NVEnc#177] opened 2019-11-28 16:35 UTC
So, here's an odd problem:

* Encode a movie with TrueHD or AC-3 to MKV with --avhw and --audio-copy.
* Audio works fine for about ~54 minutes of the movie, along with seeking within that time.
* Audio will start to break up at that point and potentially freeze your player.
* Audio not usable after that nor will seeking provide usable audio after that.
* If you re-mux the same file with MKVToolnix, the problem goes away, but I'm not positive there isn't corruption.
* Atmos + DTS tracks are fine.

**Comment by ls-milkyway** [comment] 2019-12-10 06:24
I have faced such issues...with DTS & AC3 .... I found a solution:
1) Check audio video timings (out of sync, fps mismatch etc.) using ffmpeg command.
2) Extract audio and video using mkvcleaver.
3) Merge both audio and video (with proper delay or stretch in audio track if present) also select fix bitstream timing in video trac,k with mkvtoolnix.
Finally, use nvencc

**Comment by rigaya** [comment] 2020-02-10 14:15
I think this is a problem caused by the insufficient handling of muxing, I have improved the handling of muxing in [NVEnc 4.63](https://github.com/rigaya/NVEnc/releases/tag/4.63), which might fix this issue.

**Comment by Eldenissio** [comment] 2020-02-19 16:55
I have upgraded to latest version (4.64), but I still have issues where the resulting mkv (4K with --codec hevc --avhw --audio-copy) has no TrueHD audio.
Tried multiple files with TrueHD audio source, but issue still the same.
I run Win Server 2019 OS build 17763.973, dual Xeon X5650, 40GB RAM, Nvidia Quadro P620, driver version 441.66

**Comment by rigaya** [comment] 2020-03-07 13:40
I've improved handling of muxing further, I now have no problem with copying trueHD with [NVEnc 4.68](https://github.com/rigaya/NVEnc/releases/tag/4.68).

**Comment by Eldenissio** [comment] 2020-03-08 11:06
> I've improved handling of muxing further, I now have no problem with copying trueHD with [NVEnc 4.68](https://github.com/rigaya/NVEnc/releases/tag/4.68).

Just tested, TrueHD now works fine. You're amazing, rigaya, Thank You!

**Comment by rigaya** [comment] 2020-03-09 13:36
Thank you for confirming, glad to hear it now works! I'll close this issue now.

**Closed by rigaya** 2020-03-09 13:36 UTC
