### ISSUE TITLE
Can add vmaf cuda?

### ISSUE THREAD

**Issue by claudiomarassi** [rigaya/NVEnc#546] opened 2024-01-04 03:09 UTC
https://github.com/Netflix/vmaf/tree/master/libvmaf

add -Denable_cuda=true to build with CUDA support, which requires nvcc for compilation (tested with CUDA >= 11)

https://github.com/Netflix/vmaf/releases/tag/v3.0.0

First release to include vmaf_cuda_* APIs, header file vmaf_cuda.h

**Comment by rigaya** [comment] 2024-01-05 12:10
This seems to be a duplicate of ＃543.

**Comment by claudiomarassi** [comment] 2024-01-07 02:00
Sorry.
Thanks!

**Closed** 2024-01-08 02:34 UTC
