### ISSUE TITLE
Suggestions for improvement: --video-copy

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#621] opened 2024-09-13 00:33 UTC
Since NVEncC offers better audio conversion parameters than FFmpeg (e.g. addressing of tracks via language tag: --audio-codec eng?aac --audio-bitrate eng?224), I would like to use it for converting audio tracks within video files without having to re-encode the video itself. Therefore, an option “--video-copy” would be excellent and probably also very easy to implement.

Then I could finally replace FFmpeg entirely (ffmpeg -i infile.mkv -map 0 -c:v copy -c:a aac -b:a 224k ...)

**Comment by rigaya** [comment] 2024-09-21 09:06
I'm sorry but this is duplicate of #541, there is plane to copy video stream.

**Comment by rainman74** [comment] 2024-09-21 13:06
There IS a plan or there in NO plan, as said in #541 ?

**Comment by rigaya** [comment] 2024-09-21 13:29
There is no plan for video copy, as it is out of scope for this software.

**Closed by rigaya** 2024-09-21 13:29 UTC
