### ISSUE TITLE
Bitrate issue?

### ISSUE THREAD

**Issue by jriker1** [rigaya/NVEnc#400] opened 2022-06-26 14:01 UTC
Have a file that is 66 gigs and 4k quality m2ts. and that includes 2 video streams and multiple audio  Used the below code and the output was over 100 gigs.   Output bitrate is showing thru mediainfo as 144 mb/s.  

`144 Mb/s, 3840*2064 (1.85:1), at 24.000 FPS, HEVC (Main 10@L5.1@High), HDR10`

Not sure based on the below why it's hitting that:

`NVEncC64.exe --avhw --input 00000.m2ts --output 00000.mkv  --codec h265 --tier high --level 5.1 --output-depth 10 --cqp 13 --preset quality --max-bitrate 17500 --vbv-bufsize 17500 --lookahead 32 --bframes 4 --aq-temporal --aud --repeat-headers --chromaloc 2 --colorprim bt2020 --transfer smpte2084 --colormatrix bt2020nc --colorrange limited --max-cll 0,0 --master-display copy --video-metadata copy --crop 0,48,0,48  --gop-len 0 --ref 3 --profile main10 --bref-mode middle --mv-precision Q-pel`

If relevant as it didn't do that with another file that was in an MKV container, when I did 16 cqp and 15000 for the max bitrate and vbv bufsize mediainfo would show 15,000 for the bitrate.  With this file when using those settings I ran it for a few minutes and stopped.  Resulting file was showing 44 MB/s.  Though putting the M2TS file in an MKV container to encode in case the container was an issue didn't help.

Stream of thought as I test here coming back to the post so sorry.  Also notice that qp-min and qp-max values can effect the file size of a cqp encode even though if I'm reading it right the documentation stays it won't effect that type of encode.

Tried encoding again but without the max-bitrate but cqp at 20.  Still comes back at 44GB just for the re-encoded video.

**Comment by rigaya** [comment] 2022-07-01 00:32
I might have not got the point, but if the point of the issue is that the bitrate is over the --max-bitrate set, please try using --qvbr or --vbr mode, as max-bitrate is ignored when using --cqp mode.

--cqp below 20 is rather small, it is likely to get very large output file, depending on the input file.

**Comment by jriker1** [comment] 2022-07-01 15:30
The problem I'm seeing is even though it's 4k content, the video is from the late 80's.  If I denoise the video then the results are better.  So nvenc is not handling pixilation very well.  Think that doing software encoding with crf handles it better but with my current CPU that's 8 days of 100% utilization.  Tried the denoisers that nvencc offers from AVISynth but there ends up being a lot of blur to clean it enough to get a decent file.  So I'm currently taking the source footage, opening in Premiere Pro, cleaning up as a ProRes file with NeatVideo, then opening it in nvencc64.  Kind of a convoluted process but 20 hours total is better than 8 days.  Not sure once I'm done if the HDR coloring is accurate anymore but what you going to do.

I'm used to encoding before this with CRF 13 and capping out the bitrate to 17,500 with ffmpeg.  If you have some really clean digital footage, would a CQP value of 20 or 16 or 13 or 1 be similar in size at all?  I know with CRF it was my understanding in general no matter how high or low depending on how you want to say a lower number value, it won't use more bits than it needs.

**Comment by rigaya** [comment] 2022-07-02 23:40
> If you have some really clean digital footage, would a CQP value of 20 or 16 or 13 or 1 be similar in size at all?

Generally, smaller CQP (or CRF) will tend to generate larger output file even for input which looks clean enough (except for very simple black background or smomething like that).

Denoiser which nvencc has are rather simple, if you need better denoise or degrain, you might want to use filters from Avisynth and use avs input of nvencc.

**Comment by rigaya** [comment] 2022-07-29 10:16
I'll close this issue as the question has been answered.

**Closed by rigaya** 2022-07-29 10:16 UTC
