### ISSUE TITLE
StaxRip: Video encoding using NVEnc 3.33 failed with exit code: -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#45] opened 2018-04-22 09:31 UTC
If use QTGMC() + Prefetch(), NVEnc always crash with error code -1073741819 (0xC0000005) **and each time exactly in the middle of file (50%)**. This is probably due to incorrect counting of fps after the QTGMC deinterlacing operation, and perhaps an error in StaxRip i dont know...
**I'm using NVEnc 3.33**

[Avisynth script.txt](https://github.com/rigaya/NVEnc/files/1935372/Avisynth.script.txt)

![2018-04-21](https://user-images.githubusercontent.com/11748220/39093482-0f816f4c-4629-11e8-85ea-743c076fcf8a.png)
![2018-04-21 1](https://user-images.githubusercontent.com/11748220/39093483-11d29866-4629-11e8-8604-f8d47d63c770.png)
![2018-04-21 2](https://user-images.githubusercontent.com/11748220/39093485-1392fd58-4629-11e8-8fe9-e937d38da9bd.png)

**Comment by drSHLEFF** [comment] 2018-04-26 02:45
If need CrashDump
[NVEncC64.exe.13432.zip](https://github.com/rigaya/NVEnc/files/1949513/NVEncC64.exe.13432.zip)

**Comment by rigaya** [comment] 2018-04-26 14:11
I've setup Avisynth+ with QTGMC, and tried to reproduce the issue, but unsuccessful. (Maybe different from Staxrip Environment...)

Does the problem occur in any input file?

**Binaries used**
NVEncC 3.33
Avisynth+ 0.1.0 r2580
QTGMC 3.357
Masktools2 2.2.14
MvTools2 2.7.3
NNEDI3 0.9.4.50
RgTools 0.96
SMDegrain 3.1.2.93s
AddGrainC-1.7.1
dfttest-1.9.4


**test_qtgmc.avs**
```
Import("C:\Program Files (x86)\AviSynth+\plugins64\QTGMC.avsi")
Import("C:\Program Files (x86)\AviSynth+\plugins64\smdegrain.avsi")
Import("C:\Program Files (x86)\AviSynth+\plugins64\mtmodes.avsi")

LWLibavVideoSource("input.ts", format = "YUV420P8")
QTGMC( Preset="Slower", MatchPreset="Slower", MatchPreset2="Slower", NoisePreset="Slower", SourceMatch=3, FPSDivisor=2)
Prefetch(4)
```


**log**
```
x64\NVEncC64.exe --vbrhq 6000 --preset quality --ref 5 --lookahead 32 --aq-strength 15 --aq --aq-temporal -i "Y:\Test\test_qtgmc.avs" -o F:\temp\test.264
NVEncC (x64) 3.33 (r739) by rigaya, Mar 21 2018 19:05:58 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (16299)
CPU            Intel Core i9-7980XE @ 2.60GHz [TB: 4.21GHz] (18C/36T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1708 MHz (390.77)
NVENC / CUDA   NVENC API 8.0, CUDA 9.1, schedule mode: auto
Input Buffers  CUDA, 44 frames
Input Info     Avisynth+ 2.60(yv12)->nv12 [AVX2], 1920x1080, 30000/1001 fps
Vpp Filters    copyHtoD
Output Info    H.264/AVC high @ Level auto
               1920x1080p 1:1 29.970fps (30000/1001fps)
Encoder Preset quality
Rate Control   VBRHQ
Bitrate        6000 kbps (Max: 162000 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     300 frames
B frames       3 frames
Ref frames     5 frames, LTR: off
AQ             on(spatial, temporal, strength 15)
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto


encoded 2696 frames, 3.74 fps, 6002.02 kbps, 64.36 MB
encode time 0:12:00, CPU: 9.5%, GPU: 4.6%, VE: 23.8%, GPUClock: 1625MHz, VEClock: 1469MHz
frame type IDR    9
frame type I      9,  total size   0.53 MB
frame type P    988,  total size  44.99 MB
frame type B   1699,  total size  18.84 MB
```

**Comment by pwacooijmans** [comment] 2018-05-28 19:19
Version 3.33 doesn't work well with StaxRip I had simular issues...however it's been fixed now for me. With the latest nvidia driver etc etc

**Comment by rigaya** [comment] 2024-08-11 10:43
I’ll close the issue as the problem seems to be out dated.

**Closed by rigaya** 2024-08-11 10:43 UTC
