### ISSUE TITLE
encodes with HDR10+ metadata too dark in low light scenes

### ISSUE THREAD

**Issue by cartman0208** [rigaya/NVEnc#259] opened 2020-08-14 22:32 UTC
Hi,
after some encodes with embedded HRD10+ metadata I noticed that scenes with low light are a lot darker compared to encodes without HDR10+ content
The encodes were done with the --dhdr10info parameter and the JSON was created with [hdr10plus_parser](https://github.com/quietvoid/hdr10plus_parser)
My TV is a Samsung Q90 and even with background light and brightness set to maximum dark scenes are almost not distinguishable

**Comment by cartman0208** [comment] 2020-08-17 17:56
I also like to mention that when using the --pic-struct parameter in combination with HDR10+ metadata the video shows some kind of irregular flicker, like switching between dark and bright (normal HDR and HDR10+) ... I don't know how to describe it better

**Comment by jdobbs1954** [comment] 2020-08-17 21:49
Since it appears that encodes with X265 seem to be working,  I decided to browse some HEVC files to see what is different between the original HDR10+, the X265 hevc, and the NVENCC hevc file.

In browsing the HEVC streams from X265 and NVENCC -- there is a couple things that stand out:

1. In the X265 encoded HEVC file there are two SEI prefixes added:

One SEI that contains the content light level
One SEI that contains the display mastering information

2. In the NVENCC there is only one SEI prefix that contains:

Content light level, followed by display mastering information.

3. In the original (from an authored HDR10+ UHD disc) there are also two SEI prefixes present:

One SEI that contains the content light level
One SEI that contains the display mastering information

4. It also appears that both X265 and the original add the two SEIs to every IDR frame (even if they don't change) -- while NVENCC doesn't (I assume it only changes it at what it thinks are scene changes... but I'm not sure).

Since both the original and X265 streams seem to be working... it's possible that the problem is centered around the attempt to combine both types of information into a single SEI and/or the fact that it is missing in most IDR frames.

**Comment by rigaya** [comment] 2020-09-12 14:59
[NVEnc 5.15](https://github.com/rigaya/NVEnc/releases/tag/5.15) has merged the change of the earlier test build.

**Comment by cartman0208** [comment] 2020-09-13 12:57
I just wanted to report back, with the newest release the HDR10+ content is playing fine with correct brightness.

Thanks for your work

**Comment by rigaya** [comment] 2020-09-13 13:50
Thank you for your tests, nice to hear it's fine now.

**Closed by rigaya** 2020-09-13 13:50 UTC
