### ISSUE TITLE
Can  you add more Avisynth sharpening types?

### ISSUE THREAD

**Issue by Walcund** [rigaya/NVEnc#302] opened 2021-01-28 14:00 UTC
Hello Rigaya!

Can you add more sharpening types to NVENC, because the crude "edge sharpening" is not good in many cases,

What are the best quality Avisynth  sharpeners, which are worth to consider?

Here is the sharpener list of the official webapge of Avisynth:

http://avisynth.nl/index.php/Category:Sharpeners

Best regards!
Bye!

**Comment by rigaya** [comment] 2021-01-31 12:39
For edge sharpening, we already have [--vpp-unsharp](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-unsharp-param1value1param2value2). [--vpp-edgelevel](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-edgelevel-param1value1param2value2), and [NVEnc 5.26](https://github.com/rigaya/NVEnc/releases/tag/5.26) adds awarpsharp based [--vpp-warpsharp](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-warpsharp-param1value1param2value2) in response to #294.

Which are useful will depend on the input so it is hard to tell, as they tend to have strong side effects.

**Comment by Walcund** [comment] 2021-01-31 18:32
Hi!

I used this command from the option list: https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md 
--vpp-warpsharp threshold=128,blur=3,type=1
However it resulted in error.

**Comment by rigaya** [comment] 2021-02-01 12:20
Would you please provide the full error log and the full command line option you've used? I were not able to reproduce the error using "--vpp-warpsharp threshold=128,blur=3,type=1".

**Comment by Walcund** [comment] 2021-02-02 09:53
> 
> 
> Would you please provide the full error log and the full command line option you've used? I were not able to reproduce the error using "--vpp-warpsharp threshold=128,blur=3,type=1".

NVEnc --y4m -i - --fps 25.000 --codec h265 --profile main10 --level auto --tier high --sar 1:1 --lookahead 32 --output-depth 10 --vbrhq 100000 --max-bitrate 240000 --gop-len 600 --ref 7 --multiref-l0 6 --multiref-l1 2 --nonrefp --bframes 3 --bref-mode each --mv-precision Q-pel --cu-max 32 --cu-min 8 --preset quality --videoformat ntsc --colormatrix bt709 --cuda-schedule sync --keyfile GENERATED_KEY_FILE --vpp-warpsharp threshold=128,blur=3,type=1 --output OUTPUTFILE

**Comment by rigaya** [comment] 2021-02-02 13:00
I tested the same commands, but unfortunately I couldn't reproduce the error.

What kind of error have you got? Would you prove the full log?

**Comment by Schmaenks** [comment] 2023-02-06 12:24
--vpp-unsharp radius=9,weight=0.2,threshold=0
Gives me decent results.
Not too much and not too less.

**Comment by rigaya** [comment] 2024-08-03 22:43
I’ll close the issue as there is no plan to add new filters at this time.

**Closed by rigaya** 2024-08-03 22:43 UTC
