### ISSUE TITLE
check_pts problem

### ISSUE THREAD

**Issue by WildEgoLee** [rigaya/NVEnc#377] opened 2022-02-13 05:25 UTC
Hi ,I'm using your amazing NVenc,but recently I got a error when I processed some videos,the error as following:
`2022-01-19 20:07:20,032 - check_pts(3): timestamp of video frame is smaller than previous frame, changing pts: 400 -> 1250 (previous pts 1200).`
`2022-01-19 20:07:20,039 - check_pts(6): timestamp of video frame is smaller than previous frame, changing pts: 1600 -> 2450 (previous pts 2400).`
I used `--avsync forcecfr` to try to deal with it, though this error missed,but my video and its audio became out-sync.

Wish you can give me some advice,thanks.

**Comment by rigaya** [comment] 2022-02-14 12:51
Seems like the timestamp has been decoded wrong, and encountered reversed timestamp. It's hard to say the cause of this, as it depends on the input file.

If you are using hardware decode (--avhw), switching to software decode (--avsw) might help.

**Comment by rigaya** [comment] 2022-07-29 10:18
I'll close this issue as the question has been answered.

**Closed by rigaya** 2022-07-29 10:18 UTC
