### ISSUE TITLE
Can you add high quality cuda accelerated DEGRAIN Avisynth filters?

### ISSUE THREAD

**Issue by Cuberlain** [rigaya/NVEnc#267] opened 2020-09-20 09:39 UTC
Hello Rigaya!

Can you add cuda accelerated high quality DEGRAIN Avisynth filters? Especially the highest quality computational demanding versions...

Thank you!

**Comment by rigaya** [comment] 2020-09-23 11:31
Please refer to #243, as this is a duplicate of it.

**Comment by DTL2020** [comment] 2023-07-06 10:44
That were old state of hardware and software development.

Now NVIDIA provide hardware ME (from MPEG encoder) and it can replaces MAnalyse. So developers of temporal degrain filter only need to implement much more simple MDegrainN. At least in the state of 2.7.45 mvtools version. Also the interpolated overlap is not hard to port to accelerator I hope - with some dependance between blocks processing shaders. So at the 2023 may be developers of NVenc will not be as afraid to port only small part of mvtools to make full hardware accelerated motion compensated temporal denoise filter on NVIDIA board. Also hardware ME not required MSuper with subsample calculated data and also some shader example available how to do required subsample shifting for MDegrainN. To keep full precision provided by hardware ME (up to qpel). Example of software is https://github.com/DTL2020/mvtools . It uses hardware ME via DX12 API, but I remember NVIDIA also provide some CUDA API for ME too.

**Comment by rigaya** [comment] 2024-08-03 23:08
I’ll close this issue as I will not have enough time to add degrain features, as it requires too much implementation cost , especially implementing mvtools stuff.

**Closed by rigaya** 2024-08-03 23:08 UTC
