### ISSUE TITLE
--Level (bug)

### ISSUE THREAD

**Issue by JibsouX** [rigaya/NVEnc#300] opened 2021-01-19 01:07 UTC
Hello !
I try to test an hevc encode main 10 trier high level 4.1, it create an output error : 
"Failed to initialize encoder,"
"8 (NVENC indicates that one or more of the parameter passed to the API is invalid.)"

It work well in auto and level 5 and more, but not under L5..

Encode mode : VBR HQ - Quality - @Main 10 high

**Comment by JibsouX** [comment] 2021-01-19 01:55
Update : 
It seem like it's due to the combo level 4.1 and ref more than 5.

**Comment by rigaya** [comment] 2021-01-19 15:06
Limitation of the level is related with output resolution, ref, profile, tier and max bitrate.

If you are working with output resolution of 3840x2160, ref=5 requires level 5, so this is not a bug. I would simply go for level 5.

You can check the limitation on the link below.
https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding#Tiers_and_levels

**Comment by JibsouX** [comment] 2021-01-19 16:49
Hello, i fully understand the limitation of level, but i working in FHD not more..

**Comment by SiV44** [comment] 2021-01-19 21:53
Hello,
NVEnc from rigaya, allows a maximum use of 7 reference frames, however using more than 5 (HEVC) or 4 (AVC) always fails with:

`8 (NVENC indicates that one or more of the parameter passed to the API is invalid.)`

Ever since I have been using NVEnc it has always been so, so I presume this is a limitation of the SDK.

---
Best regards

**Comment by rigaya** [comment] 2021-01-21 14:56
I think that HEVC Level 4.1 should allow 1080p with ref up to 6, but NVENC SDK seems to allows only up to 5, somehow we need level 5 for ref=7.

I'll close this issue, as I also think this is a limitation of the SDK.

**Closed by rigaya** 2021-01-21 14:56 UTC

**Comment by JibsouX** [comment] 2021-01-21 16:16
Too bad, i have made some quality compare between the limitation "level 4.1 + ref max 5" and "level 5 ref 16", and there is a great difference in the picture reconstruction.. (pixel mixings, gradients, shadows, micro details, motion details conservation.. , shame.
