### ISSUE TITLE
When encoding anamorphic video, then the aspect ratio in the target file is obtained incorrectly.

### ISSUE THREAD

**Issue by drSHLEFF** [rigaya/NVEnc#43] opened 2018-03-22 14:21 UTC
Source: DVD PAL 4:3 (1,333333) Anamorph - DAR: 1,333333 (not ITU PAL), SAR: 1,25 (720x576), PAR: 16:15;
After encoding:  We have h264 video 785x576 (AR=1,36284722) - absolutely wrong aspect, the picture turns out to be stretched. Right aspect must be - 768x576 = 1,333333 (and if use avisynth + ffmpeg - it turns out that way).
The screenshot shows that the data in the command line is transmitted correctly and NVEnc applies PAR 16:15 correctly, but the output is a video with the wrong aspect ratio.
If manualy use --dar 4:3 - doesn't change anything;

So, instead PAR=16:15 (1,0666667), NVEnc used PAR: 785/576= 1,36284722 / 1,25 = 1,0902777 - ITU PAL?? but ITU PAL 12:11 = 1,0909090;

![inked2018-03-22 36 _li](https://user-images.githubusercontent.com/11748220/37775149-38872bf0-2df3-11e8-8e65-29c47d0b6b12.jpg)
![inked2018-03-22 37 _li](https://user-images.githubusercontent.com/11748220/37775153-3a85d14a-2df3-11e8-851c-81a8752b303f.jpg)

**Comment by rigaya** [comment] 2018-03-22 14:52
I am not able to reproduce the issue.

I tried encoding below, input as 720x576, with --sar 16:15.

![image](https://user-images.githubusercontent.com/815947/37777624-5c61b300-2e2b-11e8-9d82-e3ab92df50ee.png)

The output video shows DAR=4:3 by MediaInfo, which is correct, without any problem.

![image](https://user-images.githubusercontent.com/815947/37777538-2875a22c-2e2b-11e8-8370-bf445b53b875.png)

**Comment by drSHLEFF** [comment] 2018-03-22 16:30
The error is strange, so we need a more accurate method to find it... But even in mediainfo it is clear to see that it shows the value of the aspect ratio **2 times** and it means that in this video the aspect ratio **in pixels** differs from the original. 
![inked37777538-2875a22c-2e2b-11e8-8370-bf445b53b875_li](https://user-images.githubusercontent.com/11748220/37782508-16417d82-2e04-11e8-8f81-83a0df324b46.jpg)
Just mediainfo rounds the values ​​in a fairly wide range, therefore, writes there and there 4:3, but **in pixels the values ​​are different**. In the original 4:3 = 720x576 with SAR 16:15 = 768x576. And after NVEnс it turns out 785х576(!). It is interesting that this happens exclusively with SAR=16:15. If you specify SAR= 767/720, then error in the encoded h264 will not be - the resolution will be 767x576, with SAR= 769/720 - the resolution will be 769x576, and only with SAR= 16:15 (768/720) - the resolution of the destination file becomes for some reason 785x576 ))
You should see the **real resolution of the h264** video track **in pixels** considering SAR. The easiest way to do this is to pack the resulting h264 track in mkv **manually** without any options, and then open this mkv with MKVToolNix GUI - you'll see the real video resolution of packed h264 in video properties.

The worst thing about this error is that the video gets stretched - so I found this error.

![default](https://user-images.githubusercontent.com/11748220/37782512-185877a6-2e04-11e8-8821-714b5d5c081c.PNG)

PS: Of course, you can manually set the aspect ratio in the media container, and thus work around the problem, but the error will remain and may appear, for example, in the android MX Player, which takes the original values from the h264 track - there the video will be stretched.

**Comment by rigaya** [comment] 2018-03-22 22:09
OK, I have got the same value from MKVToolnix, when I have made mkv from raw h264 ouput.

However, I checked internal calculation of NVEncC, but its display resolution is set to 768x576, and this value is sent to NVENC API, so it should have no problem.

Furthermore, if you directly output video in mkv format from NVEncC, you should also have no problem.

![image](https://user-images.githubusercontent.com/815947/37801072-8320c1e2-2e68-11e8-8119-ee261aecfc1e.png)

Please consider direct mkv output from NVEncC.

**Comment by drSHLEFF** [comment] 2018-03-23 04:01
Yes, it's very wierd. And the strangest thing is that if you use any other values of SAR (767/720, 769/720) then there is no issue - SAR values are stored correctly in the vui-parameters of the h264 header. So, the problem arises not at the moment of packing in mkv, but the output raw h264 video does have an incorrect SAR after the encoding. If you try to play raw h264 video encoded with 16:15 (768/720) SAR, then it is stretched horizontally. **The issue is, that when SAR=16:15 (768/720) is used, then its value is not saved  in the h264 header at all.**

**Comment by rigaya** [comment] 2018-04-24 13:12
720x576 with sar 16:15 should result 768x576(4:3) on display.

On NVENC SDK, application does not set sar directly, but set display size. I have checked that the value set is 768x576, without problem.

However, NVENC output sets "aspect_ratio_idc:2", which means 12:11, and this seems to cause the problem. 12:11 is sar value for 720x576 4:3 frame **with** horizontal overscan.

This is applied even if I set the overscan flag to **off** like below. ("overscan_appropriate_flag: 0")

I have not been able to figure out how to fix this problem.

```
Nal length 25 start code 4 bytes 
 ref 3 type 7 Sequence parameter set
   profile: 100
   constaint_set0_flag: 0
   constaint_set1_flag: 0
   constaint_set2_flag: 0
   constaint_set3_flag: 0
   level_idc: 31
   seq parameter set id: 0
   chroma format idx: 1
   bit depth luma minus8: 0
   bit depth chroma minus8: 0
   Qpprime Y Zero Transform Bypass flag: 0
   Seq Scaling Matrix Present Flag: 0
   log2_max_frame_num_minus4: 4
   pic_order_cnt_type: 0
    log2_max_pic_order_cnt_lsb_minus4: 4
   num_ref_frames: 3
   gaps_in_frame_num_value_allowed_flag: 0
   pic_width_in_mbs_minus1: 44 (720)
   pic_height_in_map_minus1: 35
   frame_mbs_only_flag: 1
     derived height: 576
   direct_8x8_inference_flag: 1
   frame_cropping_flag: 0
   vui_parameters_present_flag: 1
    aspect_ratio_info_present_flag: 1
     aspect_ratio_idc:2
    overscan_info_present_flag: 1
     overscan_appropriate_flag: 0
    video_signal_info_present_flag: 0
    chroma_loc_info_present_flag: 0
    timing_info_present_flag: 1
     num_units_in_tick: 1000
     time_scale: 60000
     fixed_frame_scale: 1
    nal_hrd_parameters_present_flag: 0
    vcl_hrd_parameters_present_flag: 0
    pic_struct_present_flag: 0
```

**Comment by rigaya** [comment] 2018-05-28 13:35
I have added workaround for this issue in NVEnc 4.04, by simply using h264_metadata/hevc_metadata bitstream filter of libavcodec to overwrite the sample_aspect_ratio field of the bitstream.

**Comment by drSHLEFF** [comment] 2018-05-29 11:00
cool. if I get a suitable original, I'll check it out. took note...

**Comment by pwacooijmans** [comment] 2018-05-29 11:45
I think you should disable cutting in staxrip to make it work....but that's just a thought....

**Comment by drSHLEFF** [comment] 2018-05-29 11:47
don't think

**Comment by drSHLEFF** [comment] 2018-05-29 11:49
try and sense

**Comment by rigaya** [comment] 2018-10-08 12:28
I will close this issue, please reopen if you have any related problems.

**Closed by rigaya** 2018-10-08 12:28 UTC
