### ISSUE TITLE
--dhdr10-info not working,...

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#233] opened 2020-05-24 17:44 UTC
Using:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\HDR\HDR-10+\muxing\without HDR10+ data.mp4" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f yuv4mpegpipe - | NVEncC64 --y4m -i - --fps 24.000 --codec h265 --profile main10 --level auto --tier high --sar 1:1 --lookahead 16 --output-depth 10 --vbrhq 0 --vbr-quality 0.00 --max-bitrate 240000 --gop-len 0 --ref 3 --bframes 0 --no-b-adapt --mv-precision Q-pel --preset default --colormatrix bt2020nc --max-cll 1043,23 --master-display G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(15000000,1) --dhdr10-info "F:\TestClips&Co\files\HDR\HDR-10+\muxing\HDR-10+.json" --cuda-schedule sync --output "E:\Temp\without HDR10+ data_19_40_16_7910_01.265"
```
I just get:
```
--------------------------------------------------------------------------------
E:\Temp\without HDR10+ data_19_40_16_7910_01.265
--------------------------------------------------------------------------------
NVEncC (x64) 5.02 (r1541) by rigaya, May 23 2020 19:20:00 (VC 1925/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            AMD Ryzen 7 1800X Eight-Core Processor (8C/16T)
GPU            #0: GeForce GTX 1070 Ti (2432 cores, 1683 MHz)[PCIe3x16][445.87]
NVENC / CUDA   NVENC API 9.1, CUDA 11.0, schedule mode: sync
Input Buffers  CUDA, 29 frames
Input Info     y4m(yv12(10bit))->p010 [AVX2], 3840x2160, 24/1 fps
Vpp Filters    copyHtoD
Output Info    H.265/HEVC main10 @ Level auto
               3840x2160p 1:1 24.000fps (24/1fps)
Encoder Preset default
Rate Control   VBRHQ
Bitrate        0 kbps (Max: 240000 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 16 frames, Adaptive I Insert
GOP length     240 frames
B frames       0 frames [ref mode: disabled]
Ref frames     3 frames
AQ             off
CU max / min   auto / auto
VUI            matrix:bt2020nc
MasteringDisp  G(0.170000 0.797000) B(0.131000 0.046000) R(0.708000 0.292000)
               WP(0.312700 0.329000) L(1500.000000 0.000100)
MaxCLL/MaxFALL 1043/23
Others         mv:Q-pel
```
and a 0 byte file. (first thought the json file was the problem, but same decoder call and json file work fine with x265)

**Comment by rigaya** [comment] 2020-05-25 14:31
It might be because the previous NVEnc 5.02 archive lacked hdr10plus_gen.exe, I have uploaded new archive now, please have a test.

**Comment by Selur** [comment] 2020-05-25 14:36
Nope, same effect:
```
--------------------------------------------------------------------------------
E:\Temp\without HDR10+ data_19_40_16_7910_01.265
--------------------------------------------------------------------------------
NVEncC (x64) 5.02 (r1542) by rigaya, May 23 2020 13:57:38 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (18363)
CPU            AMD Ryzen 7 1800X Eight-Core Processor (8C/16T)
GPU            #0: GeForce GTX 1070 Ti (2432 cores, 1683 MHz)[PCIe3x16][445.87]
NVENC / CUDA   NVENC API 9.1, CUDA 11.0, schedule mode: sync
Input Buffers  CUDA, 29 frames
Input Info     y4m(yv12(10bit))->p010 [AVX2], 3840x2160, 24/1 fps
Vpp Filters    copyHtoD
Output Info    H.265/HEVC main10 @ Level auto
               3840x2160p 1:1 24.000fps (24/1fps)
Encoder Preset default
Rate Control   VBRHQ
Bitrate        0 kbps (Max: 240000 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 16 frames, Adaptive I Insert
GOP length     240 frames
B frames       0 frames [ref mode: disabled]
Ref frames     3 frames
AQ             off
CU max / min   auto / auto
VUI            matrix:bt2020nc
MasteringDisp  G(0.170000 0.797000) B(0.131000 0.046000) R(0.708000 0.292000)
               WP(0.312700 0.329000) L(1500.000000 0.000100)
MaxCLL/MaxFALL 1043/23
Others         mv:Q-pel
```
0byte file no further output

**Comment by Selur** [comment] 2020-05-25 14:46
you can get the input files over at:
https://drive.google.com/drive/folders/1-PymgpSkhvYs2XmiAbX82ySLdknMPaGC
in case that helps

**Comment by mimile7984** [comment] 2020-06-06 19:36
hello, dhdr10-info not working with yhe last version of NVEnc, the encode is impossible and NVEnc crash.

**Comment by rigaya** [comment] 2020-06-07 00:32
I'm feeling this problem is not easy to fix or even find out the cause this issue, it's crashing after calling nvEncEncodePicture of the NVENC SDK API.

As a workaround, would you test without adding lookahead option? I think you can avoid this error.

**Comment by mimile7984** [comment] 2020-06-07 19:23
Thank you I have worked around this error with lookahead = 0 instead of 32

**Comment by rigaya** [comment] 2020-06-11 14:34
I have updated to [NVEnc 5.04](https://github.com/rigaya/NVEnc/releases/tag/5.04), which will automatically disable lookahead with warning message when using dhdr10-info, so you won't run into this error.

**Comment by rigaya** [comment] 2020-07-14 14:23
I'll close this issue, as we can avoid this problem by the work around added. Thank you for reporting the problem.

**Closed by rigaya** 2020-07-14 14:23 UTC
