### ISSUE TITLE
v05.07:  Using --repeat-headers Command Line Option Causes Encode Failure

### ISSUE THREAD

**Issue by jdobbs1954** [rigaya/NVEnc#247] opened 2020-07-01 01:14 UTC
**[Update]  See the edit at the end of this issue report**

Attempting to encode and UHD source using the --repeat-headers option resulted in a failure after encoding 73319 frames with error "Cannot allocate memory"  (see below).    The total source input framecount is 204478 frames.   If I remove the --repeat-headers command line option, the encode completes successfully.

**v05.07 Encode with "--repeat-headers"**

**C:\>"D:\BD_Rebuilder\tools\nvenc\nvencc.exe" --avhw --vpp-pad 0,276,0,278 -i "P:\IMPORTS\SOURCE\BDMV\STREAM\00000.m2ts" --codec hevc --preset quality --profile main10 --output-depth 10 --repeat-headers --chromaloc 2 --colorprim bt2020 --transfer smpte2084 --colormatrix bt2020nc --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) --qp-min 0 --vbr 20602 --keyfile "D:\WORKING4\WORKFILES\VID_00000.CHP" --sar 1:1 --aud --pic-struct --vbv-bufsize 45000 --max-bitrate 48000 --gop-len 24 -o "D:\WORKING4\WORKFILES\VID_00000.AVS.hevc"**

D:\WORKING4\WORKFILES\VID_00000.AVS.hevc**

NVEncC (x86) 5.07 (r1584) by rigaya, Jun 30 2020 13:46:27 (VC 1900/Win/avx2)
OS Version     Windows 10 x64 (18362)
CPU            AMD FX(tm)-8350 Eight-Core Processor (4C/8T)
GPU            #0: GeForce GTX 1660 (1408 cores, 1830 MHz)[2147483.64]
NVENC / CUDA   NVENC API 9.1, CUDA 11.0, schedule mode: auto
Input Buffers  CUDA, 16 frames
Input Info     avcuvid: H.265/HEVC, 3840x1606, 24000/1001 fps
Vpp Filters    cspconv(p010 -> yv12(16bit))
               pad: [3840x1606]->[3840x2160] (right=0, left=0, top=276, bottom=278)
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               3840x2160p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   VBR
Bitrate        20602 kbps (Max: 48000 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
QP range       I:0-51  P:0-51  B:0-51
VBV buf size   45000 kbit
Lookahead      off
GOP length     24 frames
B frames       3 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             off
CU max / min   auto / auto
VUI            matrix:bt2020nc,colorprim:bt2020,transfer:smpte2084,chromaloc:topleft
MasteringDisp  G(0.265000 0.690000) B(0.150000 0.060000) R(0.680000 0.320000)
               WP(0.312700 0.329000) L(999.999975 0.000100)
Others         mv:auto aud pic-struct repeat-headers
**avcuvid: error occured while reading file: 73419 frames, Cannot allocate memory**

encoded 73319 frames, 77.20 fps, 20840.60 kbps, 7597.31 MB
encode time 0:15:49, CPU: 14.0%, GPU: 12.4%, VE: 98.7%, VD: 16.0%
frame type IDR  3058
frame type I    3058,  total size   998.13 MB
frame type P   18331,  total size  4633.06 MB
frame type B   51930,  total size  1966.12 MB

[Edit]  The new --repeat-headers option apparently causes a memory leak.   When I run the command above without it while watching memory usage under the Windows 10 task manager -- memory is allocated and stays consistent during the entire encoding process.  If I add --repeat-headers back to the command line, I can watch the system memory usage for NENCC slowly rise until it (apparently) runs out and the process fails.  (Note that the 32 bit version of NVENCC is being used to stay compatible with possible use of AVS files -- if I attempt to use the 64 bit version it fails with a "nppc64_10.dll was not found" error -- downloading nppc64_10.dll will fix that error, but the memory leak still exists)

**Comment by rigaya** [comment] 2020-07-01 15:19
Please try with x64 build of [NVEnc 5.08](https://github.com/rigaya/NVEnc/releases/tag/5.08), it should not require nppc64_10.dll now.

It might be a memory leak but it's difficult to fix, as "--repeat-headers" only sets a parameter provided by NVENC SDK, there is little I can do here.

**Comment by jdobbs1954** [comment] 2020-07-01 17:34
Any chance you can report it to NVIDIA?   It’s a very obvious issue – as you can watch the application continually allocate more memory (in Windows Task Manager) until it eventually runs out.

**Comment by jdobbs1954** [comment] 2020-07-02 12:17
Here is some additional information that might help identify/resolve this issue.   If you change the output format from an elementary stream (.hevc) to a container (.m2ts), the memory leak seems to disappear.   Hopefully that will help in pointing out exactly where the leak is happening.

**Comment by rigaya** [comment] 2020-07-05 14:10
>  If you change the output format from an elementary stream (.hevc) to a container (.m2ts), the memory leak seems to disappear.

Thank you for the information, that was a big hint. I was able to find the cause of the memory leak, there was a leak when writing elementary stream with --sar option. The leak should be removed in [NVEnc 5.09](https://github.com/rigaya/NVEnc/releases/tag/5.09).

**Comment by jdobbs1954** [comment] 2020-07-06 12:19
I can confirm that the memory leak has been fixed.  Thank you for the quick resolution.

**Comment by rigaya** [comment] 2020-07-14 14:16
Thanks for confirming, I'll close this issue.

**Closed by rigaya** 2020-07-14 14:16 UTC
