### ISSUE TITLE
NVEncC Not responding

### ISSUE THREAD

**Issue by lstsystems** [rigaya/NVEnc#48] opened 2018-05-11 02:28 UTC
My system:
Amd Ryzen 7 2700x 
GTX 1080

When ever i run "NVEncC.exe --check-features" i get a blank response, instead of the information it stays blank and goes back to the initial command prompt. I have tried different version from 3.26 to the latest 4.01 with no change.

**Comment by lgoncal** [comment] 2018-05-13 16:47
HEVC is supported by GTX1080

**Comment by wolfhowling** [comment] 2018-05-13 16:52
The problem is not the graphic card even tho thats what the message says. When i install the the Ryzen 7 2700x with the same graphic card same OS and everything  i get this error, when i install the Intel CPU i5 back it works just fine. NVEnC will respond to some commands but not to others making it unable to do the conversion when using  it under the Ryzen CPU.

**Comment by rigaya** [comment] 2018-05-14 14:12
I've tested on Win10 x64 / R7 1700 / GTX 1080 system, but worked out fine, so I am not being able to figure out what is really causing the problem.

I have changed the code getting cpu info in NVEnc 4.02, improving the behavior when it got error, but might not work well.

**Comment by wolfhowling** [comment] 2018-08-06 23:51
In order for the --check-feature to work you have to have the on board video card enabled at all times even if you don't use it, if you disable it then the --check-feature comes back blank

**Comment by rigaya** [comment] 2024-08-03 22:20
I’ll close this issue as the problem should have been fixed.

**Closed by rigaya** 2024-08-03 22:20 UTC
