### ISSUE TITLE
NVenc --avhw unable to parse properly some movie

### ISSUE THREAD

**Issue by dan64** [rigaya/NVEnc#653] opened 2024-12-14 11:57 UTC
There are situation where NVenc --avhw is unable to parse properly the input movie.

In the attachment: [Sample_avi.zip](https://github.com/user-attachments/files/18135646/Sample_avi.zip)
there is the file "sample.avi" and some test scripts (paths to be adjusted to your location) 

Using: NVEncC.exe --avhw  -i "sample.avi" (see script: **encode_nvenc_avi.cmd**)

I get the following error:
`check_pts(1): timestamp of video frame is smaller than previous frame, skipping frame: previous pts 0, current pts 0.`
(see file: **encode_nvenc_avi.log.txt**)

converting the avi in mkv (not added to reduce attachment size) and using: NVEncC.exe --avhw  -i "sample.mkv" (see script: **encode_nvenc_mkv.cmd**)

The file is encoded but are encoded only 2808 frames out of 2830 (see file: **encode_nvenc_mkv.log.txt**)  

Finally using Vapoutsynth to parse the file using  NVEncC.exe --vpy -i "sample.vpy" (see script: **encode_nvenc_vpy.cmd**)
are encoded all the 2830 frames (see file: **encode_nvenc_vpy.log.txt**).

Could you check ?

Dan

**Comment by rigaya** [comment] 2024-12-14 12:14
Please remove ```--fps 25``` and all will be fine as below. As written in the [help](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--fps-intint-or-float) it is not recommended to use --fps with --avhw.

x64\NVEncC64.exe --avhw -i sample.avi --codec h265 --profile main10 --level auto --tier high --sar 1:1 --lookahead 16 --output-depth 10 --vbr 0 --vbr-quality 27.50 --aq --aq-strength 1 --gop-len 0 --ref 3 --bframes 5 --bref-mode auto --lookahead 16 --mv-precision Q-pel --lookahead-level 1 --preset default --colorrange limited --colormatrix smpte170m --vpp-resize algo=ngx-vsr,vsr-quality=4 --output-res 960x720 --vpp-gauss disabled --vpp-unsharp radius=3,weight=0.5,threshold=10 --vpp-tweak brightness=-0.01,contrast=1.01,gamma=0.99,saturation=1.01,hue=0,swapuv=false --cuda-schedule sync -o test.mp4

```
--------------------------------------------------------------------------------
F:\temp\test.mp4
--------------------------------------------------------------------------------
NVEncC (x64) 7.77 (r3109) by rigaya, Dec  8 2024 11:49:11 (VC 1942/Win)
OS Version     Windows 11 x64 (26100) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [3.71GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4080 (9728 cores, 2505 MHz)[PCIe4x16][565.90]
NVENC / CUDA   NVENC API 12.2, CUDA 12.7, schedule mode: sync
Input Buffers  CUDA, 32 frames
Input Info     avcuvid: MPEG4, 640x480, 25/1 fps
Vpp Filters    cspconv(nv12 -> yv12(16bit))
               resize: ngx-vsr 640x480 -> 960x720
                           ngx-vsr: colorspace: cspconv(yv12(16bit) -> yuv444(16bit))
                                       matrix:smpte170m->GBR
                                    cspconv(rgb(fp32) -> rgb32)
                                    nvsdk-ngx vsr: quality: 4
                                    cspconv(rgb32 -> rgb(fp32))
                                    colorspace: matrix:GBR->smpte170m
               unsharp: radius 3, weight 0.5, threshold 10.0
               tweak: brightness -0.01, contrast 1.01, saturation 1.01, gamma 0.99, hue 0.00, swapuv off
               cspconv(yuv444(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level auto
               960x720p 1:1 25.000fps (25/1fps)
               avwriter: hevc => mp4
Encoder Preset default
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 28800 kbps)
Target Quality 27.50
QP range       I:0-63  P:0-63  B:0-63
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 16 frames, Level 1, Adaptive I, B Insert
GOP length     250 frames
B frames       5 frames [ref mode: disabled]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on (spatial, strength 1)
CU max / min   auto / auto
VUI            matrix:smpte170m,range:limited
Others         mv:Q-pel

encoded 2830 frames, 300.55 fps, 1356.70 kbps, 18.31 MB
encode time 0:00:09, CPU: 2.8%, GPU: 85.2%, VE: 12.9%, VD: 4.9%, GPUClock: 2402MHz, VEClock: 2007MHz
frame type IDR   12
frame type I     12,  avgQP  31.08,  total size   0.25 MB
frame type P    476,  avgQP  31.80,  total size   7.79 MB
frame type B   2342,  avgQP  36.73,  total size  10.26 MB
```

**Comment by dan64** [comment] 2024-12-14 14:01
Without --fps all frames are encoded. It would be better that if is used with --avhw, NVenc ignore it as stated in help:  _Only valid for raw format (when --raw is used), otherwise it will be ignored or only treated as a hint_. Because it seems that in the current implementation is not ignored and/or is providing the wrong hint.

**Comment by rigaya** [comment] 2024-12-15 00:36
There is a case that framerate hint is required, for example reading raw images as input by --avsw/avhw, so I cannot remove that (although some cases like you faced it causes problem).

Most cases which video are in containers (like avi, mp4, mkv, ts...), framerate information can be acquired from the container, so --fps is not required.

I will close this issue as anyway the problem is solved.

**Closed by rigaya** 2024-12-15 00:36 UTC

**Comment by dan64** [comment] 2024-12-15 13:42
Sorry rigaya but I don't consider the problem solved. In the sample provided the fps information was already available in the container. So in this case the --fps provided in the command line should be ignored as stated also in the [help](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--fps-intint-or-float) . So why I have to remove it to solve the problem ?
If is ignored why is a problem if is added ?. Since in the container is already specified fps 25, why adding "--fps 25" is creating problems to NVenc ? I'm not asking to remove the parameter "--fps" from the command line, but just to ignore it in the case the information is already available in the container. Moreover is not clear what will happen if in the container is present a different "fps".
But in any case in the sample provided the fps is the same and providing "--fps 25" in the command line is hurting NVenc and this should never happen.
So on my point of view the explanation and the proposed solution is not satisfactory.

**Comment by rigaya** [comment] 2024-12-16 13:12
You can use the test build below for this which can handle this file with --fps, but it is recommended to not use --fps if not necessary.
https://nightly.link/rigaya/NVEnc/actions/runs/12350705382/NVEncC_release_r3115_x64.zip

**Comment by dan64** [comment] 2024-12-16 15:15
Now it works as expected.

Thanks,
Dan
