### ISSUE TITLE
a series of job starting getting Video encoding returned exit code: -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by chowderhead** [rigaya/NVEnc#603] opened 2024-07-21 21:29 UTC
Does any of this sikgify anything to you of something I should be doing different. 
maybe theres a buffer system i can increase in rezedit.

what do ya think rigaya.
thanks.

\_______________________________________________________________________________________________________________

Video encoding returned exit code: -1073740791 (0xC0000409)

It's unclear what this exit code means, in case it's
a Windows system error then it possibly means:

# for decimal -1073740791 / hex 0xc0000409
  STATUS_STACK_BUFFER_OVERRUN                                    ntstatus.h   
# The system detected an overrun of a stack-based buffer in
# this application. This overrun could potentially allow a
# malicious user to gain control of this application.

--------------------------- Video encoding ---------------------------

NVEncC 7.48.0

"F:\Downloads\APPS and INSTALLERS\StaxRip-v2.36.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe" --avsdll "F:\Downloads\APPS and INSTALLERS\StaxRip-v2.36.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --qvbr 29 --codec h265 --preset P7 --level 5.1 --multipass 2pass-full --qp-init 28 --qp-max 30 --qp-min 28 --max-bitrate 3500 --aq --aq-strength 1 --bframes 4 --lookahead 12 --gop-len 120 --cu-min 8 --vpp-resize algo=nvvfx-superres --vpp-convolution3d matrix=standard,ythresh=30,cthresh=10,t_ythresh=30,t_cthresh=10 --vpp-edgelevel strength=4,threshold=15,black=8 --sar 199:200 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange limited --output-buf 128 --perf-monitor-interval 2000 --vbr-quality 29 --output-res 1280x720 --mv-precision q-pel -i J:\Downloads\STAXRIP.CACHE2\Episode.01_temp\Episode.01.avs -o J:\Downloads\STAXRIP.CACHE2\Episode.01_temp\Episode.01_out.h265

--------------------------------------------------------------------------------
J:\Downloads\STAXRIP.CACHE2\Episode.01_temp\Episode.01_out.h265
--------------------------------------------------------------------------------
NVEncC (x64) 7.48 (r2793) by rigaya, Mar 28 2024 11:43:50 (VC 1929/Win)
OS Version     Windows 10 x64 (17763) [CP1252]
CPU            Intel Core i7-10750H @ 2.60GHz [TB: 4.51GHz] (6C/12T)
GPU            #0: NVIDIA GeForce RTX 2070 (2304 cores, 1455 MHz)[PCIe3x16][555.99]
NVENC / CUDA   NVENC API 12.1, CUDA 12.5, schedule mode: auto
Input Buffers  CUDA, 32 frames
Input Info     AviSynth+ 3.7.3 r4003(yv12)->nv12 [AVX2], 800x448, 24/1 fps
Vpp Filters    copyHtoD
               cspconv(nv12 -> yv12)
               convolution3d: matrix standard, mode normal
                       threshold spatial luma 30, chroma 10, temporal luma 30, chroma 10
               resize: nvvfx-superres 800x448 -> 1600x896
                           nvvfx-superres: cspconv(yv12 -> bgr(fp32))
                                           nvvfx-superres: mode: 1 (aggressive), strength 0.40
                                           cspconv(bgr(fp32) -> yv12)
                       spline36 1600x896 -> 1280x720
               edgelevel: strength 4.0, threshold 15.0, black 8.0, white 0.0
               cspconv(yv12 -> nv12)
Output Info    H.265/HEVC main @ Level 5.1
               1280x720p 180:181 24.000fps (24/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        0 kbps (Max: 3500 kbps)
Target Quality 29.00
Initial QP     I:28  P:28  B:28
QP range       I:28-30  P:28-30  B:28-30
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 12 frames, Adaptive I, B Insert
GOP length     120 frames
B frames       4 frames [ref mode: middle]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on (spatial, strength 1)
CU max / min   auto / 8
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,range:limited
Others         mv:Q-pel 
cspconv: error at convert_from_rgb_list(bgr(fp32) -> yv12): cudaErrorMisalignedAddress: The device encountered a load or store instruction on a memory address which is not aligned. This leaves the process in an inconsistent state and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched..
nvvfx-superres: Error while running filter "cspconv".
resize: Error while running filter "nvvfx-superres".
Error while running filter "resize".
Error cudaEventSynchronize: 716 (<unknown>).
ERROR: 1: [fusedConvActRunner.cpp::nvinfer1::rt::cuda::FusedConvActRunner::destroyFilterTexture::293] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaStream::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)

--------------------------- Video encoding ---------------------------

NVEncC 7.48.0

"F:\Downloads\APPS and INSTALLERS\StaxRip-v2.36.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe" --avsdll "F:\Downloads\APPS and INSTALLERS\StaxRip-v2.36.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --qvbr 29 --codec h265 --preset P7 --level 5.1 --multipass 2pass-full --qp-init 28 --qp-max 30 --qp-min 28 --max-bitrate 3500 --aq --aq-strength 1 --bframes 4 --lookahead 12 --gop-len 120 --cu-min 8 --vpp-resize algo=nvvfx-superres --vpp-convolution3d matrix=standard,ythresh=30,cthresh=10,t_ythresh=30,t_cthresh=10 --vpp-edgelevel strength=4,threshold=15,black=8 --sar 199:200 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange limited --output-buf 128 --perf-monitor-interval 2000 --vbr-quality 29 --output-res 1280x720 --mv-precision q-pel -i J:\Downloads\STAXRIP.CACHE2\Episode.01_temp\Episode.01.avs -o J:\Downloads\STAXRIP.CACHE2\Episode.01_temp\Episode.01_out.h265

--------------------------------------------------------------------------------
J:\Downloads\STAXRIP.CACHE2\Episode.01_temp\Episode.01_out.h265
--------------------------------------------------------------------------------
NVEncC (x64) 7.48 (r2793) by rigaya, Mar 28 2024 11:43:50 (VC 1929/Win)
OS Version     Windows 10 x64 (17763) [CP1252]
CPU            Intel Core i7-10750H @ 2.60GHz [TB: 4.51GHz] (6C/12T)
GPU            #0: NVIDIA GeForce RTX 2070 (2304 cores, 1455 MHz)[PCIe3x16][555.99]
NVENC / CUDA   NVENC API 12.1, CUDA 12.5, schedule mode: auto
Input Buffers  CUDA, 32 frames
Input Info     AviSynth+ 3.7.3 r4003(yv12)->nv12 [AVX2], 800x448, 24/1 fps
Vpp Filters    copyHtoD
               cspconv(nv12 -> yv12)
               convolution3d: matrix standard, mode normal
                       threshold spatial luma 30, chroma 10, temporal luma 30, chroma 10
               resize: nvvfx-superres 800x448 -> 1600x896
                           nvvfx-superres: cspconv(yv12 -> bgr(fp32))
                                           nvvfx-superres: mode: 1 (aggressive), strength 0.40
                                           cspconv(bgr(fp32) -> yv12)
                       spline36 1600x896 -> 1280x720
               edgelevel: strength 4.0, threshold 15.0, black 8.0, white 0.0
               cspconv(yv12 -> nv12)
Output Info    H.265/HEVC main @ Level 5.1
               1280x720p 180:181 24.000fps (24/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        0 kbps (Max: 3500 kbps)
Target Quality 29.00
Initial QP     I:28  P:28  B:28
QP range       I:28-30  P:28-30  B:28-30
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 12 frames, Adaptive I, B Insert
GOP length     120 frames
B frames       4 frames [ref mode: middle]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on (spatial, strength 1)
CU max / min   auto / 8
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,range:limited
Others         mv:Q-pel 
cspconv: error at convert_from_rgb_list(bgr(fp32) -> yv12): cudaErrorMisalignedAddress: The device encountered a load or store instruction on a memory address which is not aligned. This leaves the process in an inconsistent state and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched..
nvvfx-superres: Error while running filter "cspconv".
resize: Error while running filter "nvvfx-superres".
Error while running filter "resize".
Error cudaEventSynchronize: 716 (<unknown>).
ERROR: 1: [fusedConvActRunner.cpp::nvinfer1::rt::cuda::FusedConvActRunner::destroyFilterTexture::293] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaStream::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)

**Comment by rigaya** [comment] 2024-07-22 09:49
Please try removing --vpp-convolution3d, I had other report that using --vpp-convolution3d and --vpp-resize nvvfx-superres together cause this kind of problem.

Unfortunately, I'm not able to reproduce the error myself and being unable to find out the cause of this problem. Therefore, currently my suggestion is to first remove --vpp-convolution3d.

**Comment by rigaya** [comment] 2024-08-11 10:38
I’ll close this issue as the topic has been answered.

**Closed by rigaya** 2024-08-11 10:38 UTC
