### ISSUE TITLE
Error "Pixel Format" happening since the last version update

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/NVEnc#602] opened 2024-07-12 15:34 UTC
Hello,

I'm experiencing this error that began to happen with the last version. 

Input file is using --avsw as i always do. Source is a ProRes 4444XQ HDR. 

I get:
```
avsw: Invalid pixel format "" from input file.
failed to initialize file reader(s).
Failed to open input file.
Error occurred: Non-zero return code from the encoding process
```

What is causing this? Is there any command i can use to avoid this happening when encoding the files? Thanks.

**Comment by VisionHDR** [comment] 2024-07-12 18:24
I have fixed it. (added pixel format to the initial encoding command to the end to be same as the required encoding for nvencc64.)

**Comment by Demicro** [comment] 2024-07-13 17:52
It has happened to me many times. I have tried to fix the error by changing parameters but without any result. Sometimes a red letter appears with errors, other times the encoding simply gets stuck and does not advance. Other times it has worked by starting the encoding several times until it works.

**Comment by rigaya** [comment] 2024-07-13 23:42
Unfortunately, I were not able to find out what is happening in detail, as I have not got ProRes 4444XQ video files, and could not reproduce the issue. (With my iPhone camera I was only able to get 4K ProRes 422HQ).

Is it possible to have the full command line and sample input file?

**Comment by rigaya** [comment] 2024-08-17 03:06
I'll close the issue as I cannot reproduce the issue and there is no conversation with this issue for a while.

**Closed by rigaya** 2024-08-17 03:06 UTC
