### ISSUE TITLE
main444 & lossless problem

### ISSUE THREAD

**Issue by w8core** [rigaya/NVEnc#5] opened 2017-01-09 19:39 UTC
I have a GTX 1060.  Your program supports encoding main444. (http://i.hizliresim.com/VPzm5y.png)

reported : 0 ? why? (http://i.hizliresim.com/VPzb3y.png)
and lossless option is false reported.

**Comment by rigaya** [comment] 2017-01-10 12:49
Thank you for reporting. The issue is fixed with NVEnc 3.04.

**Comment by w8core** [comment] 2017-01-10 17:06
PROBLEM NOT FIXED, PROBLEM IS SAME.

**Comment by rigaya** [comment] 2017-01-10 22:06
Should be fixed with 3.05.

**Closed by rigaya** 2017-01-10 22:06 UTC
