### ISSUE TITLE
Video encoding returned exit code: -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by chowderhead** [rigaya/NVEnc#553] opened 2024-02-06 16:50 UTC
Hey rigaya,
Its me again causing trouble for you.

Can you help me figure out why the nvvfx-ssuperres kicks out this error randomly it seems

Reripping usually takes care of the issue but its a hassle redoing rips that take 20 minutes then rerip sometimes twice more to finality get finished.  The quality though id AMAZING so we work our best  issue.

Heres the rest of the log of one of them.
Thx, Randy

____________________________________________________________

--------------------------- Video encoding ---------------------------

NVEncC 7.42

"F:\Downloads\APPS and INSTALLERS\StaxRip-v2.34.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe" --avsdll "F:\Downloads\APPS and INSTALLERS\StaxRip-v2.34.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --qvbr 18 --codec h265 --preset P7 --output-depth 10 --level 5.1 --multipass 2pass-full --qp-init 18 --qp-max 20 --qp-min 18 --max-bitrate 8000 --aq --aq-strength 1 --bframes 4 --ref 8 --lookahead 12 --gop-len 120 --cu-min 8 --vpp-resize algo=nvvfx-superres --vpp-convolution3d matrix=standard,ythresh=30,cthresh=10,t_ythresh=30,t_cthresh=10 --vpp-edgelevel strength=7,threshold=25,black=12 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange limited --cuda-schedule spin --output-buf 128 --perf-monitor-interval 2000 --vbr-quality 18 --output-res 1920x1080 --mv-precision q-pel -i "F:\Downloads\STAXRIP CACHE\LOGH.G07E03_temp\LOGH.G07E03.avs" -o "F:\Downloads\STAXRIP CACHE\LOGH.G07E03_temp\LOGH.G07E03_out.h265"

--------------------------------------------------------------------------------
F:\Downloads\STAXRIP CACHE\LOGH.G07E03_temp\LOGH.G07E03_out.h265
--------------------------------------------------------------------------------
NVEncC (x64) 7.42beta1 (r2683) by rigaya, Jan 27 2024 07:27:38 (VC 1929/Win)
OS Version     Windows 10 x64 (17763) [CP1252]
CPU            Intel Core i7-10750H @ 2.60GHz [TB: 4.51GHz] (6C/12T)
GPU            #0: NVIDIA GeForce RTX 2070 (2304 cores, 1455 MHz)[PCIe3x16][551.23]
NVENC / CUDA   NVENC API 12.1, CUDA 12.4, schedule mode: spin
Input Buffers  CUDA, 32 frames
Input Info     AviSynth+ 3.7.3 r4003(yv12)->nv12 [AVX2], 960x720, 60/1 fps
Vpp Filters    copyHtoD
               cspconv(nv12 -> yv12(16bit))
               convolution3d: matrix standard, mode normal
                       threshold spatial luma 30, chroma 10, temporal luma 30, chroma 10
               resize: nvvfx-superres 960x720 -> 1920x1440
                           nvvfx-superres: cspconv(yv12(16bit) -> bgr(fp32))
                                           nvvfx-superres: mode: 1 (aggressive), strength 0.40
                                           cspconv(bgr(fp32) -> yv12(16bit))
                       spline36 1920x1440 -> 1920x1080
               edgelevel: strength 7.0, threshold 25.0, black 12.0, white 0.0
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level 5.1
               1920x1080p 1:1 60.000fps (60/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        0 kbps (Max: 8000 kbps)
Target Quality 18.00
Initial QP     I:18  P:18  B:18
QP range       I:18-20  P:18-20  B:18-20
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 12 frames, Adaptive I, B Insert
GOP length     120 frames
B frames       4 frames [ref mode: middle]
Ref frames     8 frames, MultiRef L0:auto L1:auto
AQ             on (spatial, strength 1)
CU max / min   auto / 8
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,range:limited
Others         mv:Q-pel 
cspconv: error at convert_from_rgb_list(bgr(fp32) -> yv12(16bit)): misaligned address.
nvvfx-superres: Error while running filter "cspconv".
resize: Error while running filter "nvvfx-superres".
Error while running filter "resize".
Error cudaEventSynchronize: 716 (<unknown>).
ERROR: 1: [fusedConvActRunner.cpp::nvinfer1::rt::cuda::FusedConvActRunner::destroyFilterTexture::293] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaStream::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaResources.cpp::nvinfer1::ScopedCudaEvent::~ScopedCudaEvent::24] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::29] Error Code 1: Cuda Driver (misaligned address)
ERROR: 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::deallocate::42] Error Code 1: Cuda Runtime (misaligned address)

**Comment by rigaya** [comment] 2024-02-07 11:55
I think the test build below might help, fixing misaligned access in spline36 resize. Please have a try.
https://nightly.link/rigaya/NVEnc/actions/runs/7812428833/NVEncC_release_r2691_x64.zip

If it does not help, I think we need to narrow down where the error is caused, by removing filters one by one.

**Comment by chowderhead** [comment] 2024-02-08 13:03
so it got worse.  but only on run on large files.  So 110 files are 17 minute episodes they all work fine.  but on The Introduction stories called Gaiden the story are 2 hours and yjays when things het difficult.  I have tons of ram I wonder if theres any way to leverage the excess ram I have during mvidia rendering 

 sorry.  What tests should I do next to creatte some useful data.

Thanks

**Comment by rigaya** [comment] 2024-02-08 14:20
I see... I've also tried with some files but were not able to reproduce the error...

I think we need to narrow down which filter is causing the error, as there are many options used, making it difficult to find out what is the cause.

We actually have 4 filters running, and hard to say which is the cause.
- --vpp-resize nvvfx-superres + yuv-rgb conversion
- spline36 resize (1920x1440->1920x1080)
- --vpp-convolution3d
- --vpp-edgelevel

Please have a try for steps below, and would you let me know which step make the encode run fine? In this way, it should be able to identify which filter is the problem. (I'm sorry, this will be time consuming)

1. Simplify to codec and filter options only
NVEncC64.exe -i <960x720 input> -o test.mp4 --log log1.txt -c hevc --output-depth 10 --output-res 1920x1080 --vpp-resize algo=nvvfx-superres --vpp-convolution3d matrix=standard,ythresh=30,cthresh=10,t_ythresh=30,t_cthresh=10 --vpp-edgelevel strength=7,threshold=25,black=12

2. Remove --vpp-convolution3d from 1
NVEncC64.exe -i <960x720 input> -o test.mp4 --log log2.txt -c hevc --output-depth 10 --output-res 1920x1080 --vpp-resize algo=nvvfx-superres --vpp-edgelevel strength=7,threshold=25,black=12

3. Remove --vpp-edgelevel from 2
NVEncC64.exe -i <960x720 input> -o test.mp4 --log log3.txt -c hevc --output-depth 10 --output-res 1920x1080 --vpp-resize algo=nvvfx-superres

4. Remove spline36 resize
NVEncC64.exe -i <960x720 input> -o test.mp4 --log log4.txt -c hevc --output-depth 10 --output-res 1920x**1440** --vpp-resize algo=nvvfx-superres

5. Simple resize (this should be fine...)
NVEncC64.exe -i <960x720 input> -o test.mp4 --log log5.txt -c hevc --output-depth 10 --output-res 1920x1080

**Comment by chowderhead** [comment] 2024-02-08 18:21
NO PROBLEM THANKS FOR THE LAYOUT OF TESTS ILL RUN THEM ALL WITH A FILE THAT HAS FAILED BEFORE.

**Comment by chowderhead** [comment] 2024-02-08 23:06
Im doing the testing without using staxrrip so theres no avisynth messing around in this.
Im using the release you gave me.  raw cmd prompt text  Ill upload logs in about 2.5 hours.  I picked a larger test file that errored twice.  Hope we get lucky and it bombs.  Whats the fun of error codes if they go away during teesting??  cheers

**Comment by chowderhead** [comment] 2024-02-08 23:27
These all ran fine.  I think to get to bottom of this error I need some kind of debugging log ALL THE TIME. so thaT when it does blow usually about 7% OF THE FILES i CAN CAPTURE USEFUL INFO.  i have plenty of HD space for useless lgs to catch the good one.
Tell me the command to add to Nvenc to debug all the runs.  

ONE will error and well catch it.

**Comment by chowderhead** [comment] 2024-02-08 23:39
I added -log %sourcefile% --log-level debug in ALL my runs.  were gonna catch the bug,

**Comment by chowderhead** [comment] 2024-02-09 04:44
OK heres a few logs from both staxrip and NvencC 7.42.1 THAT CRASHED.  I added those two --log and --log-level flags to give you more info hopefully so that is what the NvencC.log files are.  the others are just staxrip logs but lots of useful info.
Thx Randy
______________________________________

[LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1994.S03E073.NvencC.log](https://github.com/rigaya/NVEnc/files/14217395/LOGH.Ginga.Eiyuu.Densetsu.Main.Series.720p.1994.S03E073.NvencC.log)
[LOGH 73.NvencC.log](https://github.com/rigaya/NVEnc/files/14217396/LOGH.73.NvencC.log)
[LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1994.S03E073_staxrip.log](https://github.com/rigaya/NVEnc/files/14217397/LOGH.Ginga.Eiyuu.Densetsu.Main.Series.720p.1994.S03E073_staxrip.log)
[LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1994.S03E069.NvencC.log](https://github.com/rigaya/NVEnc/files/14217398/LOGH.Ginga.Eiyuu.Densetsu.Main.Series.720p.1994.S03E069.NvencC.log)
[LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1994.S03E069_staxrip.log](https://github.com/rigaya/NVEnc/files/14217399/LOGH.Ginga.Eiyuu.Densetsu.Main.Series.720p.1994.S03E069_staxrip.log)

**Comment by chowderhead** [comment] 2024-02-09 20:29
I feel like STAXRIP should be involved. Reason when I do just two jobs at a time no error.  so if I do 40 at once in the queue this somehow affects outcome i think. bigger the queue bigger number errors.  But why??    i think ive seen a trend in this manner.  Like memory getting cleared etc for next job but something in the queue process messes with memory by no clearing it or something.

**Comment by rigaya** [comment] 2024-02-10 01:55
Actually your logs still have all 4 filters activated, therefore there are possibility of error in each filter, so I cannot tell anything from it.

- --vpp-resize nvvfx-superres + yuv-rgb conversion
- spline36 resize (1920x1440->1920x1080)
- --vpp-convolution3d
- --vpp-edgelevel

As I've said in the previous message, please try switching off one by one, and check which filter is causing the issue.

In order to figure out the problem, we need to make things more simple.

At least, please remove --vpp-convolution3d and --vpp-edgelevel on test so that we can make sure the problem is in the nvvfx-superres. Currently, we need to think of all 4 filters, and this is making things unnecessarily complicated.

---

I'm really not sure what is going on on your PC, but I've made a test build which might improve the error, fixing another possiblity of unaligned access.
https://nightly.link/rigaya/NVEnc/actions/runs/7844244436/NVEncC_release_r2696_x64.zip

**Comment by chowderhead** [comment] 2024-02-10 08:57
I ran the new build and it errored 409 the usual misaligned address  I then turned off 3d       convolution and edgelevel and the error went away.  this is the most reproducable sequence i have had.  do you wish to examine further with the actual file or what should I do next.

**Comment by chowderhead** [comment] 2024-02-10 12:32
II think Ive got a reproducable error.  94 failed with 3d set to 30-10-30-10 TWICE.
Heres the file and the command it uses to bomb.  Remember I did this with a couple AVS scripts for Tweak and Levels adjustment.  If u want the whole script I can make a project file for you so you just open it and run with staxrip.

otherwise heres the file downlaod from my google drive.

https://drive.google.com/uc?id=1Y7JQMLr2Ru73VFuWQmCMFE6aK8wfYbs-&export=download

NVEncC 7.42.2

"F:\Downloads\APPS and INSTALLERS\StaxRip-v2.34.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe" --avsdll "F:\Downloads\APPS and INSTALLERS\StaxRip-v2.34.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --qvbr 18 --codec h265 --preset P7 --output-depth 10 --level 5.1 --multipass 2pass-full --qp-init 18 --qp-max 20 --qp-min 18 --max-bitrate 8000 --aq --aq-strength 1 --bframes 4 --ref 8 --lookahead 12 --gop-len 120 --cu-min 8 --vpp-resize algo=nvvfx-superres --vpp-convolution3d matrix=standard,ythresh=30,cthresh=10,t_ythresh=30,t_cthresh=10 --vpp-edgelevel strength=7,threshold=25,black=12 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange limited --cuda-schedule spin --output-buf 128 --perf-monitor-interval 2000 --vbr-quality 18 --output-res 1920x1080 --log "F:\Downloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1996.S04E094_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1996.S04E094.NvencC.log" --log-level debug --mv-precision q-pel -i "F:\Downloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1996.S04E094_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1996.S04E094.avs" -o "F:\Downloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1996.S04E094_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.720p.1996.S04E094_out.h265"

**Comment by chowderhead** [comment] 2024-02-10 23:05
Well I've `done 20 more and only 2 errored.  I changed the 3D convolution settings by one number up or down and usually within one try it will rip.  so I don't know the part 3D setting plays versus nvvfx-superres but its definitely looking pretty solid that the new release despite a rough start pushed through at least DOUBLE the episodes wo bomb.  so it got better on average so THANKYOU.  But it does still exist just much better now but not GONE.  plus I was ripping at 30-11-30-11 or if that failed also 29-9-29-9 and lways it would pass.   30-10-30-10 is a weird number I got through a lot of test 5 min quickrips to see saturation, whiteout, white noise, chatter video crawl color inconsistency jumping black dots that crawl around edge features etc etc on 720p upsizes. ive battled with the worst. so common when small errors are upsized suddenly very noticable at 1080p and better contrast  etc removed for best results.  But it seems to prefer 30-11 or 29-9 but 30-10 has TONS of errors as you saw me I skipped probably 30 other log files because the scatterbrain behavior of this but slowly I concentrated on 3D settings and with the new version made the 409's error down by half.  Thankyou truly.  Hours and hours of rerips on this project but better now.  Thankyou for trying to help me now please.....

tell me what to do next and ill stick this out.  Im willing to do whatever testing u like since nvvfx is gonna be very busy w these amazing results.  seriously reduce the compression size by 20%. and at such a high CQP 16 setting.  These were 720p but Blu-ray masters so they came out even better than studio could produce with some of the most powerful ripping machines around.  RARELY have I EVER seen the background white noise go down SOOOOO much to drop an already STUDIO COMPRESSED video by 20% frickin percent NEVER!.  just through AI color contrast brightness unification and white noise removal.  SIMPLY ASTOUNDING.  For a 8 core i7 laptop with 10TB SSD it does pretty amazing stuff with off the shelf technology like NvencC and StaxRip.  I cant stand handbrake.  no freedom, canned boring stuff.  Maybe they use NvencC as well, u would know.  
cheers
Raandy

**Comment by rigaya** [comment] 2024-02-11 02:19
I actually did not expect it to work by making --vpp-convolution3d and --vpp-edgelevel disabled, because it would mean that there is a problem with --vpp-convolution3d and --vpp-edgelevel.

I have rechecked the code for these 2 filters quite carefully, but could not find anything that might cause the error.

Also I tried testing your input file, but unfortunately(?) there were nothing strange, it run with no problem using your options. This might be because our system has quite different setups in many ways, different OS, different GPU, so on.

```
OS Version     Windows 11 x64 (22631) [UTF-8]
CPU            12th Gen Intel Core i9-12900K [5.19GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4080 (9728 cores, 2505 MHz)[PCIe4x16][551.23]
NVENC / CUDA   NVENC API 12.1, CUDA 12.4, schedule mode: auto
```

With everything I can come up of at this point having been done, and with the difficulty of reproducing the problem at my own system, I can no longer come up with any extra ideas. I am sorry, but please understand I'm not being able to come up of any more suggestions.

As --vpp-convolution3d might be the cause of trouble, I suggest you to disable --vpp-convolution3d and use convolution3d from Avisynth filter, it might be useful to avoid the error.
http://avisynth.nl/index.php/Convolution3D

**Comment by chowderhead** [comment] 2024-02-13 01:48
Thanks for the tip Ive successfully installed and run it through avisynth seems to all work fine.  
Im curious , what is a 409 error and why do I keep getting them in your opinion??

**Comment by rigaya** [comment] 2024-02-13 10:46
Misalignment is accessing memory in address which cannot be divided by it’s access size, but I’m not sure and actually have no idea about it’s cause this time.

Anyway, it’s nice to hear that the solution worked out fine, I’ll close the issue since we’ve got to a workaround.

**Closed by rigaya** 2024-02-13 10:46 UTC

**Comment by YKefasu** [comment] 2024-06-18 01:24
I just want to report that I also often get similar errors (0xc0000005 and 0xC0000409) after updating StaxRip to a newer version. 
It happened like from the beginning of the 2024 updates.
